/*
 * TIMER_config1.h
 *
 *  Created on: Feb 1, 2022
 *      Author: khaled
 */

#ifndef MCAL_TIMER_TIMER_CONFIG1_H_
#define MCAL_TIMER_TIMER_CONFIG1_H_
#include "TIMER_private1.h"

/*TIMER MODE OPTIONS*/
/***TIMER0***
 *	NORMAL_MODE
 *	PWM_MODE
 *	CTC_MODE
 *	FAST_PWM
 *	PHASE_PWM_
 *	FAST_PWM_ICR_MODE
 *****TIMER1****
 * TIMER1_NORMAL_MODE
 * TIMER1_PWM_MODE
 * TIMER1_CTC_MODE
 * TIMER1_FAST_PWM
 * TIMER1_PHASE_PWM
 * FAST_PWM_ICR_MODE
 */

 

/*TIMER0 PRESCALER MODE OPTIONS*/
/*
 *	No_clock_source
 *	NO_PRESCALER
 *	PRESCALER_8
 *	PRESCALER_64
 *	PRESCALER_265
 *	PRESCALER_1024
 *	EXTERNAL_SRC_FALLING
 *	EXTERNAL_SRC_RISING
 *
 *	TIMER1PRESCALER MODE OPTIONS
 *	TIMER1_No_clock_source
 *	TIMER1_NO_PRESCALER
 *	TIMER1_PRESCALER_8
 *	TIMER1_PRESCALER_64
 *	TIMER1_PRESCALER_265
 *	TIMER1_PRESCALER_265
 *	TIMER1_EXTERNAL_SRC_FALLING
 *	TIMER1EXTERNAL_SRC_RISING
 */

 

/*	timer_oc_mode*/
/* OC0_LOW
 * OC0_HIGH
 * OC0_TOGGLE
 * OC0_OFF
 * OC0_INVERTED
 * OC0_NON_INVERTED
 */


/* TIMER1 INTERRUPT OPTION*/
/*
 * OVF_INTERRUPT
 * CTC_INTERRUPT
 *DISABLE_INTERRUPT
 */

#endif /* MCAL_TIMER_TIMER_CONFIG1_H_ */
